include: package:flutterando_analysis/flutter.yaml

analyzer:
  plugins:
    - architecture_linter

architecture_linter:
  excludes:
    - "**.g.dart"

  lint_severity: error

  layers:
    - &infra
      name: "Infrastructure"
      path: "(infra)"
    - &domain
      name: "Domain"
      path: "(domain)"
    - &presentation
      name: "Presentation"
      path: "(presentation)"
    - &utils
      name: "Utils"
      path: "(utils)"

  layers_config:
    - layer: *domain
      severity: error
    - layer: *infra
      severity: error
    - layer: *presentation
      severity: error
    - layer: *utils
      severity: error
  banned_imports:
    - layer: *domain
      banned:
        - *presentation
        - *infra
        - *utils
    - layer: *infra
      banned:
        - *presentation
    - layer: *presentation
      banned:
        - *infra

linter:
  rules:
    package_api_docs: true
    public_member_api_docs: true
