name: lb_planner
description: "An application to plan your moodle assignments."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  bloc: ^8.1.4
  color_blindness: ^0.2.0
  cupertino_icons: ^1.0.6
  either_dart: ^1.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_modular: ^6.3.4
  freezed_annotation: ^2.4.4
  intl: any
  json_annotation: ^4.9.0
  logging: ^1.2.0
  mcquenji_core:
    git:
      url: https://github.com/mcquenji/mcquenji_core.git
  mcquenji_local_storage:
    git:
      url: https://github.com/mcquenji/mcquenji_local_storage.git
  path: ^1.9.0
  result_dart: ^1.1.1

dev_dependencies:
  architecture_linter: ^0.2.2
  bloc_test: ^9.1.7
  build_runner: ^2.4.11
  flutter_gen: ^5.6.0
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  flutterando_analysis: ^0.0.2
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  test: ^1.25.2

dependency_overrides:
  mcquenji_local_storage:
    path: ../mcquenji_local_storage

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/modules/auth/

flutter_gen:
  output: lib/gen/assets/
  line_length: 80

  integrations:
    flutter_svg: true
    flare_flutter: false
    rive: false
    lottie: false
