name: lb_planner
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  collection: ^1.18.0
  dio: ^5.4.3+1
  either_dart: ^1.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_gen: ^5.5.0+1
  flutter_localizations:
    sdk: flutter
  flutter_modular: ^6.3.3
  freezed_annotation: ^2.4.1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  logging: ^1.2.0
  mcquenji_core:
    git:
      url: https://github.com/mcquenji/mcquenji_core.git
  mcquenji_desktop:
    git:
      url: https://github.com/mcquenji/mcquenji_desktop.git

dev_dependencies:
  dependency_validator: ^3.2.0
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true
