name: lb_planner
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  bloc: ^8.1.4
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_modular: ^6.3.4
  mcquenji_core:
    git:
      url: https://github.com/mcquenji/mcquenji_core.git
  path: ^1.9.0

dev_dependencies:
  architecture_linter: ^0.2.2
  flutter_gen: ^5.6.0
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  flutterando_analysis: ^0.0.2

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/modules/auth/

flutter_gen:
  output: lib/gen/assets/
  line_length: 80

  integrations:
    flutter_svg: true
    flare_flutter: false
    rive: false
    lottie: false
