name: "Flutter build"
on:
  release:
    types: [published]
    branches: ['app']
  workflow_dispatch:
jobs:
 build:
   name: "Linux build"
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v3
     - uses: subosito/flutter-action@v2
       with:
         flutter-version: '3.3.3'
     - run: |
        sudo apt-get update -y
        sudo apt-get install -y ninja-build libgtk-3-dev
     - run: flutter config --enable-linux-desktop
     - run: flutter build linux --release --no-sound-null-safety
