name: "Flutter build"
on:
  release:
    types: [published]
    branches: ['app']
  workflow_dispatch:
jobs:
 build:
   name: "Linux build"
   runs-on: ubuntu-latest
   steps:
     - name: "Checkout repo"
       uses: actions/checkout@v3
     - name: "Setup flutter"
       uses: subosito/flutter-action@v2
       with:
         flutter-version: '3.3.3'
         architecture: x64
     - name: "Install dependencies"
       run: |
        sudo apt-get update -y
        sudo apt-get install -y ninja-build libgtk-3-dev
     - name: "Build"
       run: |
        flutter config --enable-linux-desktop
        flutter build linux --release --no-sound-null-safety
     - name: Archive production artifacts
       uses: actions/upload-artifact@v3
       with:
         name: lb-planer-linux
         path: build/linux/x64/release/bundle/*
